#!/usr/bin/bash
#
# Credits: @higio97
# FROM File-Sharing-Bot <https://github.com/higio97/File-Sharing-Bot/>

# Attemp to Terminate and Remove previous session
if [ ! -d .git ]; then
    git clone https://github.com/higio97/File-Sharing-Bot -b master tmp_git
    mv tmp_git/.git .
    rm -rf tmp_git
fi

# start
python3 main.py
